# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: '45.79.59.146'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/mum-shoppe
          git config pull.rebase false
          git pull https://${{ secrets.PAT }}:x-oauth-basic@github.com/bulldoguk/mum-shoppe.git master
          echo "SENDGRIDSENDKEY=${{ secrets.SENDGRIDSENDKEY }}" > .env
          echo "SERVERURL='https://mumshoppe.myhmbiz.com'" >> .env
          echo "APIKEY=''" >> .env
          echo "PROTOCOL='https://'" >> .env
          echo "APIURL='api.myhmbiz.com'" >> .env
          npm ci
          npm run build
          pm2 start
          pm2 save
